basket = ["Banana","Apples","Oranges","Blueberries"];
print(basket)
basket.remove("Banana")
print(basket)
basket.remove("Blueberries")
print(basket)
basket.append("Kiwi")
print(basket)
basket.insert(0,"Banana")
print(basket)